<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home-page-fields',
		'title' => 'Home Page Fields',
		'fields' => array (
			array (
				'key' => 'field_57cc0fdab3b2e',
				'label' => 'Banner',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc0fe8b3b2f',
				'label' => 'Active',
				'name' => 'front_banner_active',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc1034b3b30',
				'label' => 'Banner',
				'name' => 'front_banner_banner',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57cc10d8b3b31',
				'label' => 'Title',
				'name' => 'front_banner_title',
				'type' => 'text',
				'default_value' => 'High Quality <em>Services</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc1130b3b32',
				'label' => 'Description',
				'name' => 'front_banner_description',
				'type' => 'textarea',
				'default_value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57cc1152b3b33',
				'label' => 'Button Link',
				'name' => 'front_banner_button_link',
				'type' => 'text',
				'default_value' => '#/',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc04b43975d',
				'label' => 'About',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc051739761',
				'label' => 'Active',
				'name' => 'front_about_us_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc04c53975e',
				'label' => 'Title',
				'name' => 'front_about_us_title',
				'type' => 'text',
				'default_value' => 'About Us',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc04e03975f',
				'label' => 'Sub Title',
				'name' => 'front_about_us_sub_title',
				'type' => 'text',
				'default_value' => 'Welcome to <em>Proweb</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc04ec39760',
				'label' => 'Description',
				'name' => 'front_about_us_description',
				'type' => 'textarea',
				'default_value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57cc077312003',
				'label' => 'Service',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc078712004',
				'label' => 'Active',
				'name' => 'front_services_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc43cfcb95d',
				'label' => 'Banner',
				'name' => 'front_services_banner',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57cc07de12005',
				'label' => 'Title',
				'name' => 'front_services_title',
				'type' => 'text',
				'default_value' => 'What we do',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc07f412006',
				'label' => 'Sub Title',
				'name' => 'front_services_sub_title',
				'type' => 'text',
				'default_value' => 'We are here to <em>Serve you</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc07fe12007',
				'label' => 'Description',
				'name' => 'front_services_description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57cc080712008',
				'label' => 'Folio',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc082212009',
				'label' => 'Active',
				'name' => 'front_portfolio_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc08421200a',
				'label' => 'Title',
				'name' => 'front_portfolio_title',
				'type' => 'text',
				'default_value' => 'Our Portfolio',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc084b1200b',
				'label' => 'Sub Title',
				'name' => 'front_portfolio_sub_title',
				'type' => 'text',
				'default_value' => 'Our Creative <em>Works</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc08561200c',
				'label' => 'Description',
				'name' => 'front_portfolio_description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57cc086c1200d',
				'label' => 'Pricing',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc0a4223871',
				'label' => 'Active',
				'name' => 'front_pricing_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc087c1200e',
				'label' => 'Title',
				'name' => 'front_pricing_title',
				'type' => 'text',
				'default_value' => 'Our Pricing',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc08901200f',
				'label' => 'Sub Title',
				'name' => 'front_pricing_sub_title',
				'type' => 'text',
				'default_value' => 'Affordable <em>Pricing</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc089a12010',
				'label' => 'Description',
				'name' => 'front_pricing_description',
				'type' => 'textarea',
				'default_value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57cc0a99fa99a',
				'label' => 'Shop',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc0aa6fa99b',
				'label' => 'Active',
				'name' => 'front_product_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc0ae1fa99c',
				'label' => 'Title',
				'name' => 'front_product_title',
				'type' => 'text',
				'default_value' => 'Our Collection',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc0aebfa99d',
				'label' => 'Sub Title',
				'name' => 'front_product_sub_title',
				'type' => 'text',
				'default_value' => 'Choose the <em>product</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc0af5fa99e',
				'label' => 'Description',
				'name' => 'front_product_description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			
			array (
				'key' => 'field_57cc0c11fa9a9',
				'label' => 'Blog',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc0c1dfa9aa',
				'label' => 'Active',
				'name' => 'front_blog_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc0c54fa9ab',
				'label' => 'Title',
				'name' => 'front_blog_title',
				'type' => 'text',
				'default_value' => 'Recent Posts',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc0c5efa9ac',
				'label' => 'Sub Title',
				'name' => 'front_blog_sub_title',
				'type' => 'text',
				'default_value' => 'Find you Through <em>Our Blog</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc0c6afa9ad',
				'label' => 'Description',
				'name' => 'front_blog_description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_57cc0ea1568f3',
				'label' => 'Contact',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cc0eaf568f4',
				'label' => 'Active',
				'name' => 'front_contact_active',
				'type' => 'true_false',
				'message' => 'Check This Box If Want To Make This Section Visible.',
				'default_value' => 1,
			),
			array (
				'key' => 'field_57cc0ec6568f5',
				'label' => 'Title',
				'name' => 'front_contact_title',
				'type' => 'text',
				'default_value' => 'Contact Us',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc0ecf568f6',
				'label' => 'Sub Title',
				'name' => 'front_contact_sub_title',
				'type' => 'text',
				'default_value' => 'Get in <em>Touch with Us</em>',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc0ed8568f7',
				'label' => 'Description',
				'name' => 'front_contact_description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-field',
		'title' => 'Portfolio Field',
		'fields' => array (
			array (
				'key' => 'field_57cc48ea76b8f',
				'label' => 'Type',
				'name' => 'portfolio_type',
				'type' => 'select',
				'choices' => array (
					'graphicdesign' => 'Graphic Design',
					'videoedition' => 'Video Edition',
					'webdevelopment' => 'Web Development',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_pricing-fields',
		'title' => 'Pricing Fields',
		'fields' => array (
			array (
				'key' => 'field_57cc4bf2118c3',
				'label' => 'Pricing Discount',
				'name' => 'pricing_discount',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57cc4c1f118c4',
				'label' => 'Pricing Price',
				'name' => 'pricing_price',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pricing',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_services-field',
		'title' => 'Services Field',
		'fields' => array (
			array (
				'key' => 'field_57cc4290328f8',
				'label' => 'Icon Class',
				'name' => 'service_icon_class',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'service',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_team-fields',
		'title' => 'Team Fields',
		'fields' => array (
			array (
				'key' => 'field_57cc4d9d8cd0d',
				'label' => 'Team Designation',
				'name' => 'team_designation',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'team',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>